import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    'nav.brand': 'LurnAx',
    'nav.home': 'Home',
    'nav.profile': 'My Profile',
    'nav.logout': 'Logout',
    'nav.role': 'Role',
    'nav.theme': 'Theme',
    'nav.language': 'Language',
    'nav.adminDashboard': 'Admin Dashboard',
    'nav.superAdminDashboard': 'Super Admin Dashboard',

    // Login & Signup
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.createAccount': 'Create Account',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.mobileNumber': 'Mobile Number',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.register': 'Register',
    'auth.signingIn': 'Signing In...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.enterEmail': 'Enter email',
    'auth.enterPassword': 'Enter password',
    'auth.reenterPassword': 'Re-enter password',
    'auth.namePlaceholder': 'e.g. John Doe',
    'auth.mobilePlaceholder': '10-digit number',
    'auth.passwordMin': 'Min 6 characters',
    'auth.forgotText': "Enter your email address and we'll send you a token to reset your password.",
    'auth.resetText': 'Enter the reset token sent to your email to set a new password.',
    'auth.resetToken': 'Reset Token',
    'auth.newPassword': 'New Password',
    'auth.updatePassword': 'Update Password',
    'auth.resetting': 'Resetting...',
    'auth.sending': 'Sending...',
    'auth.sendResetLink': 'Send Reset Link',

    // User Dashboard
    'user.welcomeTitle': 'What would you like to learn today?',
    'user.welcomeSubtitle': 'Browse high quality educational streaming videos assigned to your pathway',
    'user.searchPlaceholder': 'Search by video title, tags, description...',
    'user.allTopics': 'All Topics',
    'user.continueWatching': '🎬 Continue Watching',
    'user.recommended': '🔥 Recommended for You',
    'user.favorites': '⭐ My Favorites',
    'user.newlyAdded': '🆕 Newly Added Lessons',
    'user.recentlyPlayed': '⌛ Recently Played',
    'filter.7days': 'Last 7 days',
    'filter.1month': 'Last 1 month',
    'filter.more1month': 'More than 1 month',
    'user.searchResults': 'Search Results',
    'user.noVideosFound': 'No videos found matching your filters.',
    'user.viewsCount': 'views',
    'user.watchedPercent': 'Watched',

    // Watch Page
    'watch.recommended': 'Recommended Lessons',
    'watch.uploadedBy': 'Uploaded By',
    'watch.tags': 'TAGS',
    'watch.resumeTitle': 'Resume watching?',
    'watch.resumeBtn': 'Resume',
    'watch.startOverBtn': 'Start Over',
    'watch.playbackSpeed': 'Speed',
    'watch.quality': 'Quality',
    'watch.volume': 'Volume',
    'watch.noRelatedVideos': 'No related videos found in',

    // Admin & Super Admin Dashboards
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage your users and uploaded content',
    'admin.superTitle': 'Platform Control Panel',
    'admin.superSubtitle': 'Welcome back, Super Admin',
    'admin.exportCsv': 'Export CSV',
    'admin.exportExcel': 'Export Excel',
    'admin.exportPdf': 'Export PDF Report',
    
    // Tabs
    'admin.tabMetrics': '📊 Metrics',
    'admin.tabUsers': '👥 My Users',
    'admin.tabUpload': '📤 Upload Video',
    'admin.tabVideos': '🎥 Uploaded Videos',
    'admin.tabAdmins': '👥 Manage Admins',
    'admin.tabCategories': '🏷️ Categories',
    'admin.tabActivity': '📜 User Activities',
    'admin.tabVideosAssign': '🎥 Videos & Assignment',

    // Metrics / Stats
    'admin.statTotalUsers': 'Total Users',
    'admin.statTotalVideos': 'Uploaded Videos',
    'admin.statTotalViews': 'Total Video Views',
    'admin.statActiveUsers': 'Total Courses',
    'admin.statTotalAdmins': 'Total Admins',
    'admin.statTotalEndUsers': 'Total End Users',
    'admin.statTotalVideosAsset': 'Total Video Assets',
    'admin.statCategories': 'Predefined Categories',
    'admin.statWatchedToday': 'Views Watched Today',
    'admin.chartTopViewed': 'Top Viewed Videos',
    'admin.chartCategoryDist': 'Category Distribution',
    'admin.chartUserEngage': 'User Engagement Stats',
    'admin.chartDailyWatch': 'Daily Watch Count',
    'admin.chartCategoryViews': 'Category-wise Total Views',
    'admin.chartUserGrowth': 'User Registration Growth',
    'admin.chartAdminUsage': 'Videos Uploaded per Admin',

    // Cloud Storage & Health
    'admin.systemHealth': '🖥️ Cloud Storage & System Health',
    'admin.storageUsage': 'Cloud Storage Usage (AWS S3)',
    'admin.storageUsed': 'S3 Storage Used',
    'admin.s3Objects': 'S3 Object Count',
    'admin.bandwidth': 'Bandwidth Consumed (Today)',
    'admin.cpuLoad': 'CPU Core Load',
    'admin.memoryUsage': 'Memory Allocation',
    'admin.apiLatency': 'API Response Latency',
    'admin.serverStatus': 'Host Server Status',
    
    // Encoding Queue
    'admin.encodingQueue': '⚙️ Video Transcoding & Ingestion Queue',
    'admin.activeJobs': 'Active Transcoding Jobs',
    'admin.jobPending': 'PENDING',
    'admin.jobProcessing': 'PROCESSING',
    'admin.jobCompleted': 'COMPLETED',

    // Video Management
    'admin.videoReview': 'Video Review & Moderation',
    'admin.clickReview': 'Click on any video row or thumbnail below to preview/moderately stream it directly.',
    'admin.playReviewBtn': 'Play / Review',
    'admin.tableThumb': 'Thumbnail',
    'admin.tableTitle': 'Title',
    'admin.tableCategory': 'Category',
    'admin.uploadTitle': 'Video Title',
    'admin.uploadDesc': 'Video Description',
    'admin.tableViews': 'Views',
    'admin.tableVisibility': 'Visibility',
    'admin.tableActions': 'Actions',
    'admin.tableUploadedBy': 'Uploaded By',
    'admin.tableAssignedAdmins': 'Assigned Admins',
    'admin.assignAdminsBtn': 'Assign Admins',
    'admin.assignModalTitle': 'Assign Video to Admins',
    'admin.assignModalText': 'Select which admins can distribute this video to their assigned end users.',
    'admin.deleteBtn': 'Delete',
    'admin.addCategoryBtn': '+ Add Category',
    
    // User Management
    'admin.addUser': '+ Add User',
    'admin.addAdmin': '+ Add Admin',
    'admin.editUser': 'Edit User',
    'admin.editAdmin': 'Edit Admin',
    'admin.saveUser': 'Save User',
    'admin.saveAdmin': 'Save Admin',
    'admin.userActivityTitle': 'Global User Watch History',
    'admin.userSearchPlaceholder': 'Search user, video title...',
    'admin.tableUser': 'User',
    'admin.tableVideo': 'Video',
    'admin.tableTimestamp': 'Timestamp',
    'admin.tableAction': 'Activity Action',
    
    // Modals & General
    'admin.cancel': 'Cancel',
    'admin.submit': 'Submit',
    'admin.saving': 'Saving...',
    'admin.loading': 'Loading...',
    'admin.edit': 'Edit',
    'admin.disable': 'Disable',
    'admin.enable': 'Enable',
    
    // Profile
    'profile.title': 'Account Settings',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.changePassword': 'Change Password',
    'profile.oldPassword': 'Old Password',
    'profile.newPassword': 'New Password',
    'profile.saveChanges': 'Save Changes',
    'profile.activeDevices': 'Active Login Devices',
    'profile.deviceAgent': 'Device / Browser',
    'profile.deviceLastLogin': 'Last Active Time',

    // Sidebar
    'sidebar.home': 'Home',
    'sidebar.explore': 'Explore',
    'sidebar.categories': 'Categories',
    'sidebar.myLearning': 'My Learning',
    'sidebar.watchLater': 'Watch Later',
    'sidebar.playlists': 'Playlists',
    'sidebar.history': 'Watch History',
    'sidebar.liked': 'Liked Videos',
    'sidebar.downloads': 'Downloads',
    'sidebar.certificates': 'Certificates',
    'sidebar.progressTracker': 'Progress Tracker',
    'sidebar.community': 'Community',
    'sidebar.settings': 'Settings',

    // Video details
    'video.instructor': 'Instructor',
    'video.difficulty': 'Difficulty',
    'video.rating': 'Rating',
    'video.views': 'Views',
    'video.bookmark': 'Bookmark',
    'video.beginner': 'Beginner',
    'video.intermediate': 'Intermediate',
    'video.advanced': 'Advanced',

    // Progress metrics
    'metrics.streak': 'Streak',
    'metrics.hoursWatched': 'Hours Watched',
    'metrics.completed': 'Completed Courses',
    'metrics.weeklyGoal': 'Weekly Goal',
    'metrics.certificatesEarned': 'Certificates Earned',

    // Analytics
    'analytics.watchAnalytics': 'Watch Analytics',
    'analytics.favoriteTopic': 'Favorite Topic',
    'analytics.completionRate': 'Completion Rate',
    'analytics.mostWatchedCategory': 'Most Watched Category',

    // Community
    'community.discussionBoards': 'Discussion Boards',
    'community.askQuestion': 'Ask a question...',
    'community.postBtn': 'Post Comment',

    // Additional User Dashboard/Playlists
    'user.myPlaylists': 'My Playlists',
    'user.watchLater': 'Watch Later',
    'user.assignedCurriculum': 'Assigned Curriculum',
    'user.watchHistory': 'Watch History',
    'user.noVideosWatched': 'No videos watched yet.',
    'user.likedVideos': 'Liked Videos',
    'user.simulatedDownloads': 'Simulated Downloads',
    'user.offlineSyncActive': 'OFFLINE SYNC ACTIVE',
    'user.backToPlaylists': 'Back to Playlists',
    'user.lastActive': 'Last active',

    // Additional Watch Page
    'watch.subscribe': 'Subscribe',
    'watch.subscribed': 'Subscribed',
    'watch.likes': 'Likes',
    'watch.dislikes': 'Dislikes',

    // Admin Menu Sections
    'admin.menu.dashboard': 'Dashboard',
    'admin.menu.admin_management': 'Admin Management',
    'admin.menu.user_management': 'User Management',
    'admin.menu.content_management': 'Content Management',
    'admin.menu.video_management': 'Video Management',
    'admin.menu.analytics': 'Analytics',
    'admin.menu.subscription_management': 'Subscription Management',
    'admin.menu.notifications': 'Notifications',
    'admin.menu.security_and_compliance': 'Security & Compliance',
    'admin.menu.reports': 'Reports',
    'admin.menu.platform_settings': 'Platform Settings',
    'admin.menu.ai_insights': 'AI Insights',
    'admin.menu.system_monitoring': 'System Monitoring',
    'admin.menu.support_center': 'Support Center',
    'admin.menu.engagement': 'Engagement',
    'admin.menu.monitoring': 'Monitoring',
    'admin.menu.settings': 'Settings',
    'admin.menu.administration': 'Administration',

    // Admin Menu Items
    'admin.menu.overview': 'Overview',
    'admin.menu.realtime': 'Real-Time Monitoring',
    'admin.menu.admins_all': 'All Admins',
    'admin.menu.admins_create': 'Create Admin',
    'admin.menu.admins_perf': 'Admin Performance',
    'admin.menu.admins_logs': 'Admin Activity Logs',
    'admin.menu.admins_perms': 'Admin Permissions',
    'admin.menu.users_all': 'All Users',
    'admin.menu.users_active': 'Active Users',
    'admin.menu.users_inactive': 'Inactive Users',
    'admin.menu.users_premium': 'Premium Users',
    'admin.menu.users_blocked': 'Blocked Users',
    'admin.menu.users_logs': 'User Activity Logs',
    'admin.menu.users_subs': 'User Subscriptions',
    'admin.menu.video_upload': 'Upload Video',
    'admin.menu.video_all': 'All Videos',
    'admin.menu.video_pending': 'Pending Videos',
    'admin.menu.video_queue': 'Processing Queue',
    'admin.menu.video_featured': 'Featured Videos',
    'admin.menu.categories': 'Categories',
    'admin.menu.tags': 'Tags',
    'admin.menu.comments_mod': 'Comments Moderation',
    'admin.menu.platform_analytics': 'Platform Analytics',
    'admin.menu.user_analytics': 'User Analytics',
    'admin.menu.video_analytics': 'Video Analytics',
    'admin.menu.engage_analytics': 'Engagement Analytics',
    'admin.menu.geo_analytics': 'Geographic Analytics',
    'admin.menu.device_analytics': 'Device Analytics',
    'admin.menu.subs_plans': 'Plans',
    'admin.menu.subs_active': 'Active Subscriptions',
    'admin.menu.subs_expired': 'Expired Subscriptions',
    'admin.menu.subs_renewals': 'Renewals',
    'admin.menu.subs_coupons': 'Coupons',
    'admin.menu.notif_push': 'Push Notifications',
    'admin.menu.notif_email': 'Email Campaigns',
    'admin.menu.notif_sms': 'SMS Campaigns',
    'admin.menu.notif_ann': 'Announcements',
    'admin.menu.sec_logs': 'Login Logs',
    'admin.menu.sec_failed': 'Failed Login Attempts',
    'admin.menu.sec_ip': 'IP Monitoring',
    'admin.menu.sec_blocked': 'Blocked IPs',
    'admin.menu.sec_audit': 'Audit Logs',
    'admin.menu.sec_roles': 'Roles & Permissions',
    'admin.menu.rep_daily': 'Daily Reports',
    'admin.menu.rep_weekly': 'Weekly Reports',
    'admin.menu.rep_monthly': 'Monthly Reports',
    'admin.menu.rep_custom': 'Custom Reports',
    'admin.menu.rep_export': 'Export Center',
    'admin.menu.set_general': 'General Settings',
    'admin.menu.set_branding': 'Branding',
    'admin.menu.set_languages': 'Languages',
    'admin.menu.set_gateway': 'Payment Gateway',
    'admin.menu.set_email': 'Email Settings',
    'admin.menu.set_sms': 'SMS Settings',
    'admin.menu.set_keys': 'API Keys',
    'admin.menu.set_security': 'Security Settings',
    'admin.menu.admin_users': 'Admin Management',
    'admin.menu.admin_roles': 'Roles & Permissions',
    'admin.menu.admin_audit': 'Audit Logs',
    'admin.menu.admin_activity': 'Activity Logs',
    'admin.menu.ai_churn': 'Churn Prediction',
    'admin.menu.ai_trending': 'Trending Videos',
    'admin.menu.ai_recs': 'User Recommendations',
    'admin.menu.ai_time': 'Best Upload Time',
    'admin.menu.engage_likes': 'Likes & Reactions',
    'admin.menu.engage_comments': 'Comments',
    'admin.menu.engage_reviews': 'Reviews & Ratings',
    'admin.menu.engage_watchlist': 'Watchlist Analytics',
    'admin.menu.mon_live': 'Live Users',
    'admin.menu.mon_sys': 'System Logs',
    'admin.menu.mon_err': 'Error Logs',
    'admin.menu.mon_storage': 'Storage Usage',
    'admin.menu.mon_transcode': 'Video Processing Status',
    
    // New Overview metrics
    'admin.dashboard.totalVideosUploaded': 'Total Videos Uploaded',
    'admin.dashboard.dailyWatchTime': 'Daily Watch Time',
    'admin.dashboard.monthlyWatchTime': 'Monthly Watch Time',
    'admin.dashboard.liveStreamsRunning': 'Live Streams Running',
    'admin.dashboard.topTrendingVideos': 'Top Trending Videos',
    'admin.dashboard.trendingCategories': 'Trending Categories',
    'admin.dashboard.watchTimePerVideo': 'Watch Time Per Video',
    'admin.dashboard.avgSessionDuration': 'Average Session Duration',
    'admin.dashboard.dropOffRate': 'Drop-off Rate',
    'admin.dashboard.completionRate': 'Completion Rate',
    'admin.dashboard.pendingApprovals': 'Pending Approvals',
    'admin.dashboard.reportedVideos': 'Reported Videos',
    'admin.statNewRegistrationsToday': 'New Registrations Today',
    
    // New Admin actions
    'admin.action.ban': 'Ban',
    'admin.action.unban': 'Unban',
    'admin.action.suspend': 'Suspend',
    'admin.action.unsuspend': 'Unsuspend',
    'admin.action.refund': 'Refund',
    'admin.action.resolve': 'Resolve',
    'admin.action.approve': 'Approve',
    'admin.action.reject': 'Reject',
    'admin.action.addAdmin': 'Add Admin',
    'admin.action.createPlan': 'Create Plan',
    'admin.action.updatePlan': 'Update Plan',
    'admin.action.deletePlan': 'Delete Plan',
    'admin.action.saveSettings': 'Save Settings',
    'admin.action.sendCampaign': 'Send Campaign',
    
    // New Analytics metrics
    'admin.analytics.dau': 'Daily Active Users (DAU)',
    'admin.analytics.mau': 'Monthly Active Users (MAU)',
    'admin.analytics.newRegistrations': 'New Registrations',
    'admin.analytics.retentionRate': 'Retention Rate',
    'admin.analytics.churnRate': 'Churn Rate',
    'admin.analytics.deviceUsage': 'Device Usage',
    'admin.analytics.revenueByRegion': 'Revenue By Region',
    'admin.analytics.premiumConversion': 'Premium Conversion Rate',
    'admin.analytics.bufferingRatio': 'Buffering Ratio',
    'admin.analytics.playbackFailures': 'Playback Failures',
    'admin.analytics.cdnPerformance': 'CDN Latency',
    
    // New Monitoring metrics
    'admin.monitoring.systemResources': 'System Resources',
    'admin.monitoring.cpuLoad': 'CPU Load',
    'admin.monitoring.ramUsage': 'RAM Usage',
    'admin.monitoring.storageUsage': 'S3 Storage Usage',
    'admin.monitoring.networkUsage': 'Network Latency',
    'admin.monitoring.liveStreamsHealth': 'Live Streaming Health',
    'admin.monitoring.bitrate': 'Bitrate',
    'admin.monitoring.fps': 'FPS',
    'admin.monitoring.failedLogins': 'Failed Logins',
    'admin.monitoring.blockedIps': 'Blocked IPs',
    'admin.monitoring.alerts': 'Live System Alerts'
  },
  hi: {
    // Navigation
    'nav.brand': 'लर्नाक्स',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.profile': 'मेरी प्रोफाइल',
    'nav.logout': 'लॉग आउट',
    'nav.role': 'भूमिका',
    'nav.theme': 'थीम',
    'nav.language': 'भाषा',
    'nav.adminDashboard': 'एडमिन डैशबोर्ड',
    'nav.superAdminDashboard': 'सुपर एडमिन डैशबोर्ड',

    // Login & Signup
    'auth.signIn': 'साइन इन करें',
    'auth.signUp': 'साइन अप करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.emailAddress': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.fullName': 'पूरा नाम',
    'auth.mobileNumber': 'मोबाइल नंबर',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से ही खाता है?',
    'auth.register': 'पंजीकरण करें',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.creatingAccount': 'खाता बनाया जा रहा है...',
    'auth.backToSignIn': 'साइन इन पर वापस जाएं',
    'auth.enterEmail': 'ईमेल दर्ज करें',
    'auth.enterPassword': 'पासवर्ड दर्ज करें',
    'auth.reenterPassword': 'पासवर्ड दोबारा दर्ज करें',
    'auth.namePlaceholder': 'जैसे: जॉन डो',
    'auth.mobilePlaceholder': '10-अंकीय संख्या',
    'auth.passwordMin': 'न्यूनतम 6 अक्षर',
    'auth.forgotText': 'अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के लिए एक टोकन भेजेंगे।',
    'auth.resetText': 'नया पासवर्ड सेट करने के लिए अपने ईमेल पर भेजा गया रीसेट टोकन दर्ज करें।',
    'auth.resetToken': 'रीसेट टोकन',
    'auth.newPassword': 'नया पासवर्ड',
    'auth.updatePassword': 'पासवर्ड अपडेट करें',
    'auth.resetting': 'रीसेट किया जा रहा है...',
    'auth.sending': 'भेजा जा रहा है...',
    'auth.sendResetLink': 'रीसेट लिंक भेजें',

    // User Dashboard
    'user.welcomeTitle': 'आज आप क्या सीखना चाहेंगे?',
    'user.welcomeSubtitle': 'अपने लर्निंग पाथवे के लिए सौंपे गए उच्च गुणवत्ता वाले शैक्षिक वीडियो देखें',
    'user.searchPlaceholder': 'वीडियो शीर्षक, टैग, विवरण द्वारा खोजें...',
    'user.allTopics': 'सभी विषय',
    'user.continueWatching': '🎬 देखना जारी रखें',
    'user.recommended': '🔥 आपके लिए अनुशंसित',
    'user.favorites': '⭐ मेरे पसंदीदा',
    'user.newlyAdded': '🆕 नए जोड़े गए पाठ',
    'user.recentlyPlayed': '⌛ हाल ही में चलाए गए',
    'filter.7days': 'पिछले 7 दिन',
    'filter.1month': 'पिछला 1 महीना',
    'filter.more1month': '1 महीने से अधिक',
    'user.searchResults': 'खोज परिणाम',
    'user.noVideosFound': 'आपके फ़िल्टर से मेल खाता कोई वीडियो नहीं मिला।',
    'user.viewsCount': 'व्यूज',
    'user.watchedPercent': 'देखा गया',

    // Watch Page
    'watch.recommended': 'अनुशंसित पाठ',
    'watch.uploadedBy': 'अपलोडकर्ता',
    'watch.tags': 'टैग',
    'watch.resumeTitle': 'देखना फिर से शुरू करें?',
    'watch.resumeBtn': 'फिर से शुरू करें',
    'watch.startOverBtn': 'शुरू से देखें',
    'watch.playbackSpeed': 'गति',
    'watch.quality': 'गुणवत्ता',
    'watch.volume': 'आवाज़',
    'watch.noRelatedVideos': 'कोई संबंधित वीडियो नहीं मिला',

    // Admin & Super Admin Dashboards
    'admin.title': 'एडमिन डैशबोर्ड',
    'admin.subtitle': 'अपने उपयोगकर्ताओं और अपलोड की गई सामग्री का प्रबंधन करें',
    'admin.superTitle': 'प्लेटफ़ॉर्म कंट्रोल पैनल',
    'admin.superSubtitle': 'वापसी पर स्वागत है, सुपर एडमिन',
    'admin.exportCsv': 'सीएसवी निर्यात',
    'admin.exportExcel': 'एक्सेल निर्यात',
    'admin.exportPdf': 'पीडीएफ रिपोर्ट निर्यात',
    
    // Tabs
    'admin.tabMetrics': '📊 मेट्रिक्स',
    'admin.tabUsers': '👥 मेरे उपयोगकर्ता',
    'admin.tabUpload': '📤 वीडियो अपलोड',
    'admin.tabVideos': '🎥 अपलोड किए गए वीडियो',
    'admin.tabAdmins': '👥 एडमिन प्रबंधित करें',
    'admin.tabCategories': '🏷️ श्रेणियां',
    'admin.tabActivity': '📜 उपयोगकर्ता गतिविधियां',
    'admin.tabVideosAssign': '🎥 वीडियो और असाइनमेंट',

    // Metrics / Stats
    'admin.statTotalUsers': 'कुल उपयोगकर्ता',
    'admin.statTotalVideos': 'अपलोड किए गए वीडियो',
    'admin.statTotalViews': 'कुल वीडियो व्यूज',
    'admin.statActiveUsers': 'कुल पाठ्यक्रम',
    'admin.statTotalAdmins': 'कुल एडमिन',
    'admin.statTotalEndUsers': 'कुल अंतिम उपयोगकर्ता',
    'admin.statTotalVideosAsset': 'कुल वीडियो संपत्ति',
    'admin.statCategories': 'पूर्व परिभाषित श्रेणियां',
    'admin.statWatchedToday': 'आज देखे गए वीडियो',
    'admin.chartTopViewed': 'सबसे ज्यादा देखे गए वीडियो',
    'admin.chartCategoryDist': 'श्रेणी वितरण',
    'admin.chartUserEngage': 'उपयोगकर्ता सहभागिता आँकड़े',
    'admin.chartDailyWatch': 'दैनिक वीडियो व्यूज संख्या',
    'admin.chartCategoryViews': 'श्रेणीवार कुल व्यूज',
    'admin.chartUserGrowth': 'उपयोगकर्ता पंजीकरण वृद्धि',
    'admin.chartAdminUsage': 'प्रति एडमिन अपलोड वीडियो',

    // Cloud Storage & Health
    'admin.systemHealth': '🖥️ क्लाउड स्टोरेज और सिस्टम हेल्थ',
    'admin.storageUsage': 'क्लाउड स्टोरेज उपयोग (AWS S3)',
    'admin.storageUsed': 'S3 स्टोरेज उपयोग किया गया',
    'admin.s3Objects': 'S3 ऑब्जेक्ट गणना',
    'admin.bandwidth': 'बैंडविड्थ खपत (आज)',
    'admin.cpuLoad': 'सीपीयू कोर लोड',
    'admin.memoryUsage': 'मेमोरी आवंटन',
    'admin.apiLatency': 'एपीआई प्रतिक्रिया विलंबता',
    'admin.serverStatus': 'होस्ट सर्वर स्थिति',
    
    // Encoding Queue
    'admin.encodingQueue': '⚙️ वीडियो ट्रांसकोडिंग और प्रोसेसिंग कतार',
    'admin.activeJobs': 'सक्रिय ट्रांसकोडिंग जॉब्स',
    'admin.jobPending': 'लंबित (PENDING)',
    'admin.jobProcessing': 'प्रसंस्करण (PROCESSING)',
    'admin.jobCompleted': 'पूरा हुआ (COMPLETED)',

    // Video Management
    'admin.videoReview': 'वीडियो समीक्षा और सुधार',
    'admin.clickReview': 'सीधे वीडियो चलाने/समीक्षा करने के लिए नीचे किसी भी वीडियो रो या थंबनेल पर क्लिक करें।',
    'admin.playReviewBtn': 'चलाएं / समीक्षा',
    'admin.tableThumb': 'थंबनेल',
    'admin.tableTitle': 'शीर्षक',
    'admin.tableCategory': 'श्रेणी',
    'admin.uploadTitle': 'वीडियो का शीर्षक',
    'admin.uploadDesc': 'वीडियो का विवरण',
    'admin.tableViews': 'व्यूज',
    'admin.tableVisibility': 'दृश्यता',
    'admin.tableActions': 'कार्रवाई',
    'admin.tableUploadedBy': 'अपलोडकर्ता',
    'admin.tableAssignedAdmins': 'सौंपे गए एडमिन',
    'admin.assignAdminsBtn': 'एडमिन सौंपें',
    'admin.assignModalTitle': 'एडमिन को वीडियो सौंपें',
    'admin.assignModalText': 'चुनें कि कौन से एडमिन इस वीडियो को अपने सौंपे गए उपयोगकर्ताओं को वितरित कर सकते हैं।',
    'admin.deleteBtn': 'हटाएं',
    'admin.addCategoryBtn': '+ श्रेणी जोड़ें',
    
    // User Management
    'admin.addUser': '+ उपयोगकर्ता जोड़ें',
    'admin.addAdmin': '+ एडमिन जोड़ें',
    'admin.editUser': 'उपयोगकर्ता संपादित करें',
    'admin.editAdmin': 'एडमिन संपादित करें',
    'admin.saveUser': 'उपयोगकर्ता सहेजें',
    'admin.saveAdmin': 'एडमिन सहेजें',
    'admin.userActivityTitle': 'वैश्विक उपयोगकर्ता इतिहास',
    'admin.userSearchPlaceholder': 'उपयोगकर्ता, वीडियो शीर्षक खोजें...',
    'admin.tableUser': 'उपयोगकर्ता',
    'admin.tableVideo': 'वीडियो',
    'admin.tableTimestamp': 'समय',
    'admin.tableAction': 'गतिविधि कार्रवाई',
    
    // Modals & General
    'admin.cancel': 'रद्द करें',
    'admin.submit': 'जमा करें',
    'admin.saving': 'सहेजा जा रहा है...',
    'admin.loading': 'लोड हो रहा है...',
    'admin.edit': 'संपादित करें',
    'admin.disable': 'अक्षम करें',
    'admin.enable': 'सक्षम करें',
    
    // Profile
    'profile.title': 'खाता सेटिंग्स',
    'profile.updateSuccess': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.oldPassword': 'पुराना पासवर्ड',
    'profile.newPassword': 'नया पासवर्ड',
    'profile.saveChanges': 'परिवर्तन सहेजें',
    'profile.activeDevices': 'सक्रिय लॉगिन उपकरण',
    'profile.deviceAgent': 'उपकरण / ब्राउज़र',
    'profile.deviceLastLogin': 'अंतिम सक्रिय समय',

    // Sidebar
    'sidebar.home': 'मुख्य पृष्ठ',
    'sidebar.explore': 'खोजें',
    'sidebar.categories': 'श्रेणियां',
    'sidebar.myLearning': 'मेरी शिक्षा',
    'sidebar.watchLater': 'बाद में देखें',
    'sidebar.playlists': 'प्लेलिस्ट',
    'sidebar.history': 'देखने का इतिहास',
    'sidebar.liked': 'पसंद किए गए वीडियो',
    'sidebar.downloads': 'डाउनलोड',
    'sidebar.certificates': 'प्रमाण पत्र',
    'sidebar.progressTracker': 'प्रगति ट्रैकर',
    'sidebar.community': 'समुदाय',
    'sidebar.settings': 'सेटिंग्स',

    // Video details
    'video.instructor': 'शिक्षक',
    'video.difficulty': 'कठिनाई',
    'video.rating': 'रेटिंग',
    'video.views': 'दृश्य',
    'video.bookmark': 'बुकमार्क',
    'video.beginner': 'शुरुआती',
    'video.intermediate': 'मध्यम',
    'video.advanced': 'उन्नत',

    // Progress metrics
    'metrics.streak': 'लगातार दिन (Streak)',
    'metrics.hoursWatched': 'घंटे देखे गए',
    'metrics.completed': 'पूरे किए गए पाठ्यक्रम',
    'metrics.weeklyGoal': 'सापहतिक लक्ष्य',
    'metrics.certificatesEarned': 'अर्जित प्रमाण पत्र',

    // Analytics
    'analytics.watchAnalytics': 'देखने का विश्लेषण',
    'analytics.favoriteTopic': 'पसंदीदा विषय',
    'analytics.completionRate': 'पूर्णता दर',
    'analytics.mostWatchedCategory': 'सबसे ज्यादा देखी गई श्रेणी',

    // Community
    'community.discussionBoards': 'चर्चा मंच',
    'community.askQuestion': 'कोई प्रश्न पूछें...',
    'community.postBtn': 'टिप्पणी पोस्ट करें',

    // Additional User Dashboard/Playlists
    'user.myPlaylists': 'मेरी प्लेलिस्ट',
    'user.watchLater': 'बाद में देखें',
    'user.assignedCurriculum': 'सौंपा गया पाठ्यक्रम',
    'user.watchHistory': 'देखने का इतिहास',
    'user.noVideosWatched': 'अभी तक कोई वीडियो नहीं देखा गया।',
    'user.likedVideos': 'पसंद किए गए वीडियो',
    'user.simulatedDownloads': 'सिम्युलेटेड डाउनलोड',
    'user.offlineSyncActive': 'ऑफ़लाइन सिंक सक्रिय',
    'user.backToPlaylists': 'प्लेलिस्ट पर वापस जाएं',
    'user.lastActive': 'अंतिम सक्रिय',

    // Additional Watch Page
    'watch.subscribe': 'सदस्यता लें',
    'watch.subscribed': 'सदस्यता ली गई',
    'watch.likes': 'पसंद',
    'watch.dislikes': 'नापसंद',

    // Admin Menu Sections
    'admin.menu.dashboard': 'डैशबोर्ड',
    'admin.menu.admin_management': 'एडमिन प्रबंधन',
    'admin.menu.user_management': 'उपयोगकर्ता प्रबंधन',
    'admin.menu.content_management': 'सामग्री प्रबंधन',
    'admin.menu.video_management': 'वीडियो प्रबंधन',
    'admin.menu.analytics': 'विश्लेषण',
    'admin.menu.subscription_management': 'सदस्यता प्रबंधन',
    'admin.menu.notifications': 'सूचनाएं',
    'admin.menu.security_and_compliance': 'सुरक्षा और अनुपालन',
    'admin.menu.reports': 'रिपोर्ट',
    'admin.menu.platform_settings': 'प्लेटफ़ॉर्म सेटिंग्स',
    'admin.menu.ai_insights': 'एआई अंतर्दृष्टि',
    'admin.menu.system_monitoring': 'सिस्टम मॉनिटरिंग',
    'admin.menu.support_center': 'सहायता केंद्र',
    'admin.menu.engagement': 'सहभागिता',
    'admin.menu.monitoring': 'निगरानी',
    'admin.menu.settings': 'सेटिंग्स',
    'admin.menu.administration': 'प्रशासन',

    // Admin Menu Items
    'admin.menu.overview': 'अवलोकन',
    'admin.menu.realtime': 'वास्तविक समय निगरानी',
    'admin.menu.admins_all': 'सभी एडमिन',
    'admin.menu.admins_create': 'एडमिन बनाएं',
    'admin.menu.admins_perf': 'एडमिन प्रदर्शन',
    'admin.menu.admins_logs': 'एडमिन गतिविधि लॉग',
    'admin.menu.admins_perms': 'एडमिन अनुमतियां',
    'admin.menu.users_all': 'सभी उपयोगकर्ता',
    'admin.menu.users_active': 'सक्रिय उपयोगकर्ता',
    'admin.menu.users_inactive': 'निष्क्रिय उपयोगकर्ता',
    'admin.menu.users_premium': 'प्रीमियम उपयोगकर्ता',
    'admin.menu.users_blocked': 'अवरुद्ध उपयोगकर्ता',
    'admin.menu.users_logs': 'उपयोगकर्ता गतिविधि लॉग',
    'admin.menu.users_subs': 'उपयोगकर्ता सदस्यता',
    'admin.menu.video_upload': 'वीडियो अपलोड',
    'admin.menu.video_all': 'सभी वीडियो',
    'admin.menu.video_pending': 'लंबित वीडियो',
    'admin.menu.video_queue': 'प्रोसेसिंग कतार',
    'admin.menu.video_featured': 'विशेष वीडियो',
    'admin.menu.categories': 'श्रेणियां',
    'admin.menu.tags': 'टैग',
    'admin.menu.comments_mod': 'टिप्पणी नियंत्रण',
    'admin.menu.platform_analytics': 'प्लेटफ़ॉर्म विश्लेषण',
    'admin.menu.user_analytics': 'उपयोगकर्ता विश्लेषण',
    'admin.menu.video_analytics': 'वीडियो विश्लेषण',
    'admin.menu.engage_analytics': 'सहभागिता विश्लेषण',
    'admin.menu.geo_analytics': 'भौगोलिक विश्लेषण',
    'admin.menu.device_analytics': 'डिवाइस विश्लेषण',
    'admin.menu.subs_plans': 'योजनाएं',
    'admin.menu.subs_active': 'सक्रिय सदस्यता',
    'admin.menu.subs_expired': 'समाप्त सदस्यता',
    'admin.menu.subs_renewals': 'नवीनीकरण',
    'admin.menu.subs_coupons': 'कूपन',
    'admin.menu.notif_push': 'पुश सूचनाएं',
    'admin.menu.notif_email': 'ईमेल अभियान',
    'admin.menu.notif_sms': 'एसएमएस अभियान',
    'admin.menu.notif_ann': 'घोषणाएं',
    'admin.menu.sec_logs': 'लॉगिन लॉग',
    'admin.menu.sec_failed': 'विफल लॉगिन प्रयास',
    'admin.menu.sec_ip': 'आईपी निगरानी',
    'admin.menu.sec_blocked': 'अवरुद्ध आईपी',
    'admin.menu.sec_audit': 'ऑडिट लॉग',
    'admin.menu.sec_roles': 'भूमिकाएं और अनुमतियां',
    'admin.menu.rep_daily': 'दैनिक रिपोर्ट',
    'admin.menu.rep_weekly': 'साप्ताहिक रिपोर्ट',
    'admin.menu.rep_monthly': 'मासिक रिपोर्ट',
    'admin.menu.rep_custom': 'कस्टम रिपोर्ट',
    'admin.menu.rep_export': 'निर्यात केंद्र',
    'admin.menu.set_general': 'सामान्य सेटिंग्स',
    'admin.menu.set_branding': 'ब्रांडिंग',
    'admin.menu.set_languages': 'भाषाएं',
    'admin.menu.set_gateway': 'भुगतान गेटवे',
    'admin.menu.set_email': 'ईमेल सेटिंग्स',
    'admin.menu.set_sms': 'एसएमएस सेटिंग्स',
    'admin.menu.set_keys': 'एपीआई कुंजियाँ',
    'admin.menu.set_security': 'सुरक्षा सेटिंग्स',
    'admin.menu.admin_users': 'एडमिन प्रबंधन',
    'admin.menu.admin_roles': 'भूमिकाएं और अनुमतियां',
    'admin.menu.admin_audit': 'ऑडिट लॉग',
    'admin.menu.admin_activity': 'गतिविधि लॉग',
    'admin.menu.ai_churn': 'मंथन भविष्यवाणी',
    'admin.menu.ai_trending': 'ट्रेंडिंग वीडियो',
    'admin.menu.ai_recs': 'उपयोगकर्ता सिफारिशें',
    'admin.menu.ai_time': 'सर्वश्रेष्ठ अपलोड समय',
    'admin.menu.engage_likes': 'पसंद और प्रतिक्रियाएं',
    'admin.menu.engage_comments': 'टिप्पणियां',
    'admin.menu.engage_reviews': 'समीक्षाएं और रेटिंग',
    'admin.menu.engage_watchlist': 'वॉचलिस्ट विश्लेषण',
    'admin.menu.mon_live': 'सक्रिय उपयोगकर्ता',
    'admin.menu.mon_sys': 'सिस्टम लॉग',
    'admin.menu.mon_err': 'त्रुटि लॉग',
    'admin.menu.mon_storage': 'स्टोरेज उपयोग',
    'admin.menu.mon_transcode': 'वीडियो प्रोसेसिंग स्थिति',
    
    // New Overview metrics
    'admin.dashboard.totalVideosUploaded': 'कुल अपलोड किए गए वीडियो',
    'admin.dashboard.dailyWatchTime': 'दैनिक देखने का समय',
    'admin.dashboard.monthlyWatchTime': 'मासिक देखने का समय',
    'admin.dashboard.liveStreamsRunning': 'सक्रिय लाइव स्ट्रीम',
    'admin.dashboard.topTrendingVideos': 'शीर्ष ट्रेंडिंग वीडियो',
    'admin.dashboard.trendingCategories': 'ट्रेंडिंग श्रेणियां',
    'admin.dashboard.watchTimePerVideo': 'प्रति वीडियो देखने का समय',
    'admin.dashboard.avgSessionDuration': 'औसत सत्र अवधि',
    'admin.dashboard.dropOffRate': 'ड्रॉप-ऑफ दर',
    'admin.dashboard.completionRate': 'पूर्णता दर',
    'admin.dashboard.pendingApprovals': 'लंबित अनुमोदन',
    'admin.dashboard.reportedVideos': 'रिपोर्ट किए गए वीडियो',
    'admin.statNewRegistrationsToday': 'आज नए पंजीकरण',
    
    // New Admin actions
    'admin.action.ban': 'प्रतिबंधित करें (Ban)',
    'admin.action.unban': 'प्रतिबंध हटाएं (Unban)',
    'admin.action.suspend': 'निलंबित करें (Suspend)',
    'admin.action.unsuspend': 'निलंबन हटाएं (Unsuspend)',
    'admin.action.refund': 'धनवापसी (Refund)',
    'admin.action.resolve': 'सुलझाएं (Resolve)',
    'admin.action.approve': 'स्वीकार करें',
    'admin.action.reject': 'अस्वीकार करें',
    'admin.action.addAdmin': 'एडमिन जोड़ें',
    'admin.action.createPlan': 'योजना बनाएं',
    'admin.action.updatePlan': 'योजना अपडेट करें',
    'admin.action.deletePlan': 'योजना हटाएं',
    'admin.action.saveSettings': 'सेटिंग्स सहेजें',
    'admin.action.sendCampaign': 'अभियान भेजें',
    
    // New Analytics metrics
    'admin.analytics.dau': 'दैनिक सक्रिय उपयोगकर्ता (DAU)',
    'admin.analytics.mau': 'मासिक सक्रिय उपयोगकर्ता (MAU)',
    'admin.analytics.newRegistrations': 'नए पंजीकरण',
    'admin.analytics.retentionRate': 'प्रतिधारण दर (Retention)',
    'admin.analytics.churnRate': 'मंथन दर (Churn)',
    'admin.analytics.deviceUsage': 'डिवाइस उपयोग',
    'admin.analytics.revenueByRegion': 'क्षेत्रवार राजस्व',
    'admin.analytics.premiumConversion': 'प्रीमियम रूपांतरण दर',
    'admin.analytics.bufferingRatio': 'बफ़रिंग अनुपात',
    'admin.analytics.playbackFailures': 'प्लेबैक विफलताएं',
    'admin.analytics.cdnPerformance': 'सीडीएन विलंबता (CDN Latency)',
    
    // New Monitoring metrics
    'admin.monitoring.systemResources': 'सिस्टम संसाधन',
    'admin.monitoring.cpuLoad': 'सीपीयू लोड',
    'admin.monitoring.ramUsage': 'रैम उपयोग',
    'admin.monitoring.storageUsage': 'S3 स्टोरेज उपयोग',
    'admin.monitoring.networkUsage': 'नेटवर्क विलंबता',
    'admin.monitoring.liveStreamsHealth': 'लाइव स्ट्रीम स्वास्थ्य',
    'admin.monitoring.bitrate': 'बिटरेट (Bitrate)',
    'admin.monitoring.fps': 'एफपीएस (FPS)',
    'admin.monitoring.failedLogins': 'विफल लॉगिन',
    'admin.monitoring.blockedIps': 'अवरुद्ध आईपी',
    'admin.monitoring.alerts': 'लाइव सिस्टम अलर्ट'
  },
  kn: {
    // Navigation
    'nav.brand': 'ಲರ್ನಾಕ್ಸ್',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'nav.role': 'ಪಾತ್ರ',
    'nav.theme': 'ಥೀಮ್',
    'nav.language': 'ಭಾಷೆ',
    'nav.adminDashboard': 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.superAdminDashboard': 'ಸೂಪರ್ ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',

    // Login & Signup
    'auth.signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.signUp': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.createAccount': 'ಖಾತೆ ರಚಿಸಿ',
    'auth.emailAddress': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.confirmPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
    'auth.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.mobileNumber': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'auth.rememberMe': 'ನನ್ನನ್ನು ನೆನಪಿನಲ್ಲಿಡಿ',
    'auth.forgotPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    'auth.dontHaveAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.alreadyHaveAccount': 'ಖಾತೆ ಈಗಾಗಲೇ ಇದೆಯೇ?',
    'auth.register': 'ನೋಂದಾಯಿಸಿ',
    'auth.signingIn': 'ಸೈನ್ ಇನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'auth.creatingAccount': 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'auth.backToSignIn': 'ಮರಳಿ ಲಾಗಿನ್ ಪುಟಕ್ಕೆ',
    'auth.enterEmail': 'ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'auth.enterPassword': 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'auth.reenterPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರು-ನಮೂದಿಸಿ',
    'auth.namePlaceholder': 'ಉದಾ: ಜಾನ್ ಡೋ',
    'auth.mobilePlaceholder': '10-ಅಂಕಿಯ ಸಂಖ್ಯೆ',
    'auth.passwordMin': 'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು',
    'auth.forgotText': 'ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಲು ನಾವು ನಿಮಗೆ ಟೋಕನ್ ಕಳುಹಿಸುತ್ತೇವೆ.',
    'auth.resetText': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಲು ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಲಾದ ರೀಸೆಟ್ ಟೋಕನ್ ನಮೂದಿಸಿ.',
    'auth.resetToken': 'ರೀಸೆಟ್ ಟೋಕನ್',
    'auth.newPassword': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    'auth.updatePassword': 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
    'auth.resetting': 'ಮರುಹೊಂದಿಸಲಾಗುತ್ತಿದೆ...',
    'auth.sending': 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    'auth.sendResetLink': 'ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸಿ',

    // User Dashboard
    'user.welcomeTitle': 'ಇಂದು ನೀವು ಏನನ್ನು ಕಲಿಯಲು ಬಯಸುತ್ತೀರಿ?',
    'user.welcomeSubtitle': 'ನಿಮ್ಮ ಕಲಿಕೆಯ ಮಾರ್ಗಕ್ಕೆ ನಿಯೋಜಿಸಲಾದ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಶೈಕ್ಷಣಿಕ ವೀಡಿಯೊಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'user.searchPlaceholder': 'ವಿಡಿಯೋ ಶೀರ್ಷಿಕೆ, ಟ್ಯಾಗ್‌ಗಳು, ವಿವರಣೆಯ ಮೂಲಕ ಹುಡುಕಿ...',
    'user.allTopics': 'ಎಲ್ಲಾ ವಿಷಯಗಳು',
    'user.continueWatching': '🎬 ನೋಡುವುದನ್ನು ಮುಂದುವರಿಸಿ',
    'user.recommended': '🔥 ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    'user.favorites': '⭐ ನನ್ನ ಮೆಚ್ಚಿನವುಗಳು',
    'user.newlyAdded': '🆕 ಹೊಸದಾಗಿ ಸೇರಿಸಲಾದ ಪಾಠಗಳು',
    'user.recentlyPlayed': '⌛ ಇತ್ತೀಚೆಗೆ ಪ್ಲೇ ಮಾಡಲಾದ',
    'filter.7days': 'ಕಳೆದ 7 ದಿನಗಳು',
    'filter.1month': 'ಕಳೆದ 1 ತಿಂಗಳು',
    'filter.more1month': '1 ತಿಂಗಳಿಗಿಂತ ಹೆಚ್ಚು',
    'user.searchResults': 'ಹುಡುಕಾಟದ ಫಲಿತಾಂಶಗಳು',
    'user.noVideosFound': 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಯಾವುದೇ ವೀಡಿಯೊಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    'user.viewsCount': 'ವೀಕ್ಷಣೆಗಳು',
    'user.watchedPercent': 'ವೀಕ್ಷಿಸಲಾಗಿದೆ',

    // Watch Page
    'watch.recommended': 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಪಾಠಗಳು',
    'watch.uploadedBy': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದವರು',
    'watch.tags': 'ಟ್ಯಾಗ್‌ಗಳು',
    'watch.resumeTitle': 'ವೀಡಿಯೊವನ್ನು ಮುಂದುವರಿಸಬೇಕೆ?',
    'watch.resumeBtn': 'ಮುಂದುವರಿಸಿ',
    'watch.startOverBtn': 'ಮೊದಲಿನಿಂದ ನೋಡಿ',
    'watch.playbackSpeed': 'ವೇಗ',
    'watch.quality': 'ಗುಣಮಟ್ಟ',
    'watch.volume': 'ಧ್ವನಿ ಮಟ್ಟ',
    'watch.noRelatedVideos': 'ಯಾವುದೇ ಸಂಬಂಧಿತ ವೀಡಿಯೊಗಳು ಕಂಡುಬಂದಿಲ್ಲ',

    // Admin & Super Admin Dashboards
    'admin.title': 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'admin.subtitle': 'ನಿಮ್ಮ ಬಳಕೆದಾರರು ಮತ್ತು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ವಿಷಯವನ್ನು ನಿರ್ವಹಿಸಿ',
    'admin.superTitle': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ನಿಯಂತ್ರಣ ಫಲಕ',
    'admin.superSubtitle': 'ಮರಳಿ ಸುಸ್ವಾಗತ, ಸೂಪರ್ ಅಡ್ಮಿನ್',
    'admin.exportCsv': 'CSV ರಫ್ತು ಮಾಡಿ',
    'admin.exportExcel': 'Excel ರಫ್ತು ಮಾಡಿ',
    'admin.exportPdf': 'PDF ವರದಿ ರಫ್ತು ಮಾಡಿ',
    
    // Tabs
    'admin.tabMetrics': '📊 ಅಂಕಿಅಂಶಗಳು',
    'admin.tabUsers': '👥 ನನ್ನ ಬಳಕೆದಾರರು',
    'admin.tabUpload': '📤 ವಿಡಿಯೋ ಅಪ್‌ಲೋಡ್',
    'admin.tabVideos': '🎥 ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ವೀಡಿಯೊಗಳು',
    'admin.tabAdmins': '👥 ಅಡ್ಮಿನ್ ನಿರ್ವಹಣೆ',
    'admin.tabCategories': '🏷️ ವಿಭಾಗಗಳು',
    'admin.tabActivity': '📜 ಬಳಕೆದಾರರ ಚಟುವಟಿಕೆಗಳು',
    'admin.tabVideosAssign': '🎥 ವೀಡಿಯೊಗಳು ಮತ್ತು ನಿಯೋಜನೆ',

    // Metrics / Stats
    'admin.statTotalUsers': 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    'admin.statTotalVideos': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ವೀಡಿಯೊಗಳು',
    'admin.statTotalViews': 'ಒಟ್ಟು ವೀಡಿಯೊ ವೀಕ್ಷಣೆಗಳು',
    'admin.statActiveUsers': 'ಒಟ್ಟು ಕೋರ್ಸ್‌ಗಳು',
    'admin.statTotalAdmins': 'ಒಟ್ಟು ಅಡ್ಮಿನ್‌ಗಳು',
    'admin.statTotalEndUsers': 'ಒಟ್ಟು ಅಂತಿಮ ಬಳಕೆದಾರರು',
    'admin.statTotalVideosAsset': 'ಒಟ್ಟು ವಿಡಿಯೋ ಸ್ವತ್ತುಗಳು',
    'admin.statCategories': 'ಪೂರ್ವನಿರ್ಧರಿತ ವಿಭಾಗಗಳು',
    'admin.statWatchedToday': 'ಇಂದು ವೀಕ್ಷಿಸಿದ ಒಟ್ಟು ವೀಡಿಯೊಗಳು',
    'admin.chartTopViewed': 'ಹೆಚ್ಚು ವೀಕ್ಷಿಸಿದ ವೀಡಿಯೊಗಳು',
    'admin.chartCategoryDist': 'ವಿಭಾಗದ ಹಂಚಿಕೆ',
    'admin.chartUserEngage': 'ಬಳಕೆದಾರರ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆಯ ವಿವರಗಳು',
    'admin.chartDailyWatch': 'ದೈನಂದಿನ ವೀಕ್ಷಣೆಗಳ ಸಂಖ್ಯೆ',
    'admin.chartCategoryViews': 'ವಿಭಾಗವಾರು ಒಟ್ಟು ವೀಕ್ಷಣೆಗಳು',
    'admin.chartUserGrowth': 'ಬಳಕೆದಾರರ ನೋಂದಣಿ ಬೆಳವಣಿಗೆ',
    'admin.chartAdminUsage': 'ಪ್ರತಿ ಅಡ್ಮಿನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ವೀಡಿಯೊಗಳು',

    // Cloud Storage & Health
    'admin.systemHealth': '🖥️ ಕ್ಲೌಡ್ ಸ್ಟೋರೇಜ್ ಮತ್ತು ಸಿಸ್ಟಮ್ ಹೆಲ್ತ್',
    'admin.storageUsage': 'ಕ್ಲೌಡ್ ಸ್ಟೋರೇಜ್ ಬಳಕೆ (AWS S3)',
    'admin.storageUsed': 'S3 ಸ್ಟೋರೇಜ್ ಬಳಸಲಾಗಿದೆ',
    'admin.s3Objects': 'S3 ಫೈಲ್‌ಗಳ ಸಂಖ್ಯೆ',
    'admin.bandwidth': 'ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್ ಬಳಕೆ (ಇಂದು)',
    'admin.cpuLoad': 'CPU ಲೋಡ್',
    'admin.memoryUsage': 'ಮೆಮೊರಿ ಬಳಕೆ',
    'admin.apiLatency': 'API ರೆಸ್ಪಾನ್ಸ್ ವೇಗ',
    'admin.serverStatus': 'ಸರ್ವರ್ ಸ್ಥಿತಿ',
    
    // Encoding Queue
    'admin.encodingQueue': '⚙️ ವೀಡಿಯೊ ಪ್ರೊಸೆಸಿಂಗ್ ಮತ್ತು ಎನ್ಕೋಡಿಂಗ್ ಕ್ಯೂ',
    'admin.activeJobs': 'ಸಕ್ರಿಯ ಎನ್ಕೋಡಿಂಗ್ ಕಾರ್ಯಗಳು',
    'admin.jobPending': 'ಬಾಕಿ ಇದೆ (PENDING)',
    'admin.jobProcessing': 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ (PROCESSING)',
    'admin.jobCompleted': 'ಪೂರ್ಣಗೊಂಡಿದೆ (COMPLETED)',

    // Video Management
    'admin.videoReview': 'ವಿಡಿಯೋ ಪರಿಶೀಲನೆ ಮತ್ತು ನಿಯಂತ್ರಣ',
    'admin.clickReview': 'ವಿಡಿಯೋವನ್ನು ನೇರವಾಗಿ ಪ್ಲೇ ಮಾಡಲು ಅಥವಾ ಪರಿಶೀಲಿಸಲು ಕೆಳಗಿನ ಯಾವುದೇ ವಿಡಿಯೋ ಸಾಲು ಅಥವಾ ತಂಬ್‌ನೇಲ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'admin.playReviewBtn': 'ಪ್ಲೇ ಮಾಡಿ / ಪರಿಶೀಲಿಸಿ',
    'admin.tableThumb': 'ತಂಬ್‌ನೇಲ್',
    'admin.tableTitle': 'ಶೀರ್ಷಿಕೆ',
    'admin.tableCategory': 'ವಿಭಾಗ',
    'admin.uploadTitle': 'ವೀಡಿಯೊ ಶೀರ್ಷಿಕೆ',
    'admin.uploadDesc': 'ವೀಡಿಯೊ ವಿವರಣೆ',
    'admin.tableViews': 'ವೀಕ್ಷಣೆಗಳು',
    'admin.tableVisibility': 'ದೃಶ್ಯತೆ',
    'admin.tableActions': 'ಕ್ರಮಗಳು',
    'admin.tableUploadedBy': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದವರು',
    'admin.tableAssignedAdmins': 'ನಿಯೋಜಿಸಲಾದ ಅಡ್ಮಿನ್‌ಗಳು',
    'admin.assignAdminsBtn': 'ಅಡ್ಮಿನ್‌ಗಳನ್ನು ನಿಯೋಜಿಸಿ',
    'admin.assignModalTitle': 'ಅಡ್ಮಿನ್‌ಗಳಿಗೆ ವಿಡಿಯೋ ನಿಯೋಜಿಸಿ',
    'admin.assignModalText': 'ಯಾವ ಅಡ್ಮಿನ್‌ಗಳು ಈ ವಿಡಿಯೋವನ್ನು ತಮ್ಮ ಬಳಕೆದಾರರಿಗೆ ಹಂಚಿಕೊಳ್ಳಬಹುದು ಎಂಬುದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.',
    'admin.deleteBtn': 'ಅಳಿಸಿ',
    'admin.addCategoryBtn': '+ ವಿಭಾಗ ಸೇರಿಸಿ',
    
    // User Management
    'admin.addUser': '+ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ',
    'admin.addAdmin': '+ ಅಡ್ಮಿನ್ ಸೇರಿಸಿ',
    'admin.editUser': 'ಬಳಕೆದಾರರನ್ನು ಸಂಪಾದಿಸಿ',
    'admin.editAdmin': 'ಅಡ್ಮಿನ್ ಸಂಪಾದಿಸಿ',
    'admin.saveUser': 'ಬಳಕೆದಾರರನ್ನು ಉಳಿಸಿ',
    'admin.saveAdmin': 'ಅಡ್ಮಿನ್ ಉಳಿಸಿ',
    'admin.userActivityTitle': 'ಬಳಕೆದಾರರ ವೀಕ್ಷಣೆ ಇತಿಹಾಸ',
    'admin.userSearchPlaceholder': 'ಬಳಕೆದಾರ, ವಿಡಿಯೋ ಶೀರ್ಷಿಕೆ ಹುಡುಕಿ...',
    'admin.tableUser': 'ಬಳಕೆದಾರ',
    'admin.tableVideo': 'ವಿಡಿಯೋ',
    'admin.tableTimestamp': 'ಸಮಯ',
    'admin.tableAction': 'ಚಟುವಟಿಕೆ',
    
    // Modals & General
    'admin.cancel': 'ರದ್ದು ಮಾಡಿ',
    'admin.submit': 'ಸಲ್ಲಿಸು',
    'admin.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'admin.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'admin.edit': 'ಸಂಪಾದಿಸು',
    'admin.disable': 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸು',
    'admin.enable': 'ಸಕ್ರಿಯಗೊಳಿಸು',
    
    // Profile
    'profile.title': 'ಖಾತೆಯ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'profile.updateSuccess': 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    'profile.changePassword': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    'profile.oldPassword': 'ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್',
    'profile.newPassword': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    'profile.saveChanges': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'profile.activeDevices': 'ಸಕ್ರಿಯ ಲಾಗಿನ್ ಸಾಧನಗಳು',
    'profile.deviceAgent': 'ಸಾಧನ / ಬ್ರೌಸರ್',
    'profile.deviceLastLogin': 'ಕೊನೆಯದಾಗಿ ಸಕ್ರಿಯವಾಗಿದ್ದ ಸಮಯ',

    // Sidebar
    'sidebar.home': 'ಮುಖಪುಟ',
    'sidebar.explore': 'ಅನ್ವೇಷಿಸಿ',
    'sidebar.categories': 'ವಿಭಾಗಗಳು',
    'sidebar.myLearning': 'ನನ್ನ ಕಲಿಕೆ',
    'sidebar.watchLater': 'ನಂತರ ವೀಕ್ಷಿಸಿ',
    'sidebar.playlists': 'ಪ್ಲೇಪಟ್ಟಿಗಳು',
    'sidebar.history': 'ವೀಕ್ಷಣೆ ಇತಿಹಾಸ',
    'sidebar.liked': 'ಇಷ್ಟಪಟ್ಟ ವೀಡಿಯೊಗಳು',
    'sidebar.downloads': 'ಡೌನ್‌ಲೋಡ್‌ಗಳು',
    'sidebar.certificates': 'ಪ್ರಮಾಣಪತ್ರಗಳು',
    'sidebar.progressTracker': 'ಪ್ರಗತಿ ಟ್ರ್ಯಾಕರ್',
    'sidebar.community': 'ಸಮುದಾಯ',
    'sidebar.settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',

    // Video details
    'video.instructor': 'ಬೋಧಕರು',
    'video.difficulty': 'ಕಠಿಣತೆ',
    'video.rating': 'ರೇಟಿಂಗ್',
    'video.views': 'ವೀಕ್ಷಣೆಗಳು',
    'video.bookmark': 'ಬುಕ್ಮಾರ್ಕ್',
    'video.beginner': 'ಪ್ರಾರಂಭಿಕ',
    'video.intermediate': 'ಮಧ್ಯಂತರ',
    'video.advanced': 'ಸುಧಾರಿತ',

    // Progress metrics
    'metrics.streak': 'ನಿರಂತರ ದಿನಗಳು (Streak)',
    'metrics.hoursWatched': 'ವೀಕ್ಷಿಸಿದ ಗಂಟೆಗಳು',
    'metrics.completed': 'ಪೂರ್ಣಗೊಂಡ ಕೋರ್ಸ್‌ಗಳು',
    'metrics.weeklyGoal': 'ಸಾಪ್ತಾಹಿಕ ಗುರಿ',
    'metrics.certificatesEarned': 'ಗಳಿಸಿದ ಪ್ರಮಾಣಪತ್ರಗಳು',

    // Analytics
    'analytics.watchAnalytics': 'ವೀಕ್ಷಣೆ ವಿಶ್ಲೇಷಣೆ',
    'analytics.favoriteTopic': 'ಮೆಚ್ಚಿನ ವಿಷಯ',
    'analytics.completionRate': 'ಪೂರ್ಣಗೊಂಡ ದರ',
    'analytics.mostWatchedCategory': 'ಹೆಚ್ಚು ವೀಕ್ಷಿಸಿದ ವಿಭಾಗ',

    // Community
    'community.discussionBoards': 'ಚರ್ಚಾ ವೇದಿಕೆಗಳು',
    'community.askQuestion': 'ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    'community.postBtn': 'ಕಾಮೆಂಟ್ ಪೋಸ್ಟ್ ಮಾಡಿ',

    // Additional User Dashboard/Playlists
    'user.myPlaylists': 'ನನ್ನ ಪ್ಲೇಪಟ್ಟಿಗಳು',
    'user.watchLater': 'ನಂತರ ವೀಕ್ಷಿಸಿ',
    'user.assignedCurriculum': 'ನಿಯೋಜಿಸಲಾದ ಪಠ್ಯಕ್ರಮ',
    'user.watchHistory': 'ವೀಕ್ಷಣೆ ಇತಿಹಾಸ',
    'user.noVideosWatched': 'ಇನ್ನೂ ಯಾವುದೇ ವೀಡಿಯೊಗಳನ್ನು ವೀಕ್ಷಿಸಿಲ್ಲ.',
    'user.likedVideos': 'ಇಷ್ಟಪಟ್ಟ ವೀಡಿಯೊಗಳು',
    'user.simulatedDownloads': 'ಅನುಕರಿಸಿದ ಡೌನ್‌ಲೋಡ್‌ಗಳು',
    'user.offlineSyncActive': 'ಆಫ್‌ಲೈನ್ ಸಿಂಕ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    'user.backToPlaylists': 'ಪ್ಲೇಪಟ್ಟಿಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    'user.lastActive': 'ಕೊನೆಯದಾಗಿ ಸಕ್ರಿಯ',

    // Additional Watch Page
    'watch.subscribe': 'ಚಂದಾದಾರರಾಗಿ',
    'watch.subscribed': 'ಚಂದಾದಾರರಾಗಿದ್ದಾರೆ',
    'watch.likes': 'ಇಷ್ಟಗಳು',
    'watch.dislikes': 'ಅಸಮ್ಮತಿಗಳು',

    // Admin Menu Sections
    'admin.menu.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'admin.menu.admin_management': 'ಅಡ್ಮಿನ್ ನಿರ್ವಹಣೆ',
    'admin.menu.user_management': 'ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ',
    'admin.menu.content_management': 'ವಿಷಯ ನಿರ್ವಹಣೆ',
    'admin.menu.video_management': 'ವೀಡಿಯೊ ನಿರ್ವಹಣೆ',
    'admin.menu.analytics': 'ಅಂಕಿಅಂಶಗಳು',
    'admin.menu.subscription_management': 'ಚಂದಾದಾರಿಕೆ ನಿರ್ವಹಣೆ',
    'admin.menu.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'admin.menu.security_and_compliance': 'ಭದ್ರತೆ ಮತ್ತು ಅನುಸರಣೆ',
    'admin.menu.reports': 'ವರದಿಗಳು',
    'admin.menu.platform_settings': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'admin.menu.ai_insights': 'AI ಒಳನೋಟಗಳು',
    'admin.menu.system_monitoring': 'ಸಿಸ್ಟಮ್ ಮಾನಿಟರಿಂಗ್',
    'admin.menu.support_center': 'ಬೆಂಬಲ ಕೇಂದ್ರ',
    'admin.menu.engagement': 'ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ',
    'admin.menu.monitoring': 'ಮೇಲ್ವಿಚಾರಣೆ',
    'admin.menu.settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    'admin.menu.administration': 'ಆಡಳಿತ',

    // Admin Menu Items
    'admin.menu.overview': 'ಅವಲೋಕನ',
    'admin.menu.realtime': 'ನೈಜ-ಸಮಯದ ಮಾನಿಟರಿಂಗ್',
    'admin.menu.admins_all': 'ಎಲ್ಲಾ ಅಡ್ಮಿನ್‌ಗಳು',
    'admin.menu.admins_create': 'ಅಡ್ಮಿನ್ ರಚಿಸಿ',
    'admin.menu.admins_perf': 'ಅಡ್ಮಿನ್ ಪ್ರದರ್ಶನ',
    'admin.menu.admins_logs': 'ಅಡ್ಮಿನ್ ಚಟುವಟಿಕೆ ಲಾಗ್‌ಗಳು',
    'admin.menu.admins_perms': 'ಅಡ್ಮಿನ್ ಅನುಮತಿಗಳು',
    'admin.menu.users_all': 'ಎಲ್ಲಾ ಬಳಕೆದಾರರು',
    'admin.menu.users_active': 'ಸಕ್ರಿಯ ಬಳಕೆದಾರರು',
    'admin.menu.users_inactive': 'ನಿಷ್ಕ್ರಿಯ ಬಳಕೆದಾರರು',
    'admin.menu.users_premium': 'ಪ್ರೀಮಿಯಂ ಬಳಕೆದಾರರು',
    'admin.menu.users_blocked': 'ಬ್ಲಾಕ್ ಮಾಡಿದ ಬಳಕೆದಾರರು',
    'admin.menu.users_logs': 'ಬಳಕೆದಾರರ ಚಟುವಟಿಕೆ ಲಾಗ್‌ಗಳು',
    'admin.menu.users_subs': 'ಬಳಕೆದಾರರ ಚಂದಾದಾರಿಕೆಗಳು',
    'admin.menu.video_upload': 'ವಿಡಿಯೋ ಅಪ್‌ಲೋಡ್',
    'admin.menu.video_all': 'ಎಲ್ಲಾ ವೀಡಿಯೊಗಳು',
    'admin.menu.video_pending': 'ಬಾಕಿ ಇರುವ ವೀಡಿಯೊಗಳು',
    'admin.menu.video_queue': 'ಪ್ರಕ್ರಿಯೆ ಕ್ಯೂ',
    'admin.menu.video_featured': 'ವೈಶಿಷ್ಟ್ಯಗೊಳಿಸಿದ ವೀಡಿಯೊಗಳು',
    'admin.menu.categories': 'ವಿಭಾಗಗಳು',
    'admin.menu.tags': 'ಟ್ಯಾಗ್‌ಗಳು',
    'admin.menu.comments_mod': 'ಕಾಮೆಂಟ್‌ಗಳ ಮಾಡರೇಶನ್',
    'admin.menu.platform_analytics': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.user_analytics': 'ಬಳಕೆದಾರರ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.video_analytics': 'ವಿಡಿಯೋ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.engage_analytics': 'ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆಯ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.geo_analytics': 'ಭೌಗೋಳಿಕ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.device_analytics': 'ಸಾಧನ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.subs_plans': 'ಯೋಜನೆಗಳು',
    'admin.menu.subs_active': 'ಸಕ್ರಿಯ ಚಂದಾದಾರಿಕೆಗಳು',
    'admin.menu.subs_expired': 'ಅವಧಿ ಮುಗಿದ ಚಂದಾದಾರಿಕೆಗಳು',
    'admin.menu.subs_renewals': 'ನವೀಕರಣಗಳು',
    'admin.menu.subs_coupons': 'ಕೂಪನ್‌ಗಳು',
    'admin.menu.notif_push': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
    'admin.menu.notif_email': 'ಇಮೇಲ್ ಪ್ರಚಾರಗಳು',
    'admin.menu.notif_sms': 'SMS ಪ್ರಚಾರಗಳು',
    'admin.menu.notif_ann': 'ಘೋಷಣೆಗಳು',
    'admin.menu.sec_logs': 'ಲಾಗಿನ್ ಲಾಗ್‌ಗಳು',
    'admin.menu.sec_failed': 'ವಿಫಲ ಲಾಗಿನ್ ಯತ್ನಗಳು',
    'admin.menu.sec_ip': 'IP ಮಾನಿಟರಿಂಗ್',
    'admin.menu.sec_blocked': 'ಬ್ಲಾಕ್ ಮಾಡಲಾದ IPಗಳು',
    'admin.menu.sec_audit': 'ಆಡಿಟ್ ಲಾಗ್‌ಗಳು',
    'admin.menu.sec_roles': 'ಪಾತ್ರಗಳು ಮತ್ತು ಅನುಮತಿಗಳು',
    'admin.menu.rep_daily': 'ದೈನಂದಿನ ವರದಿಗಳು',
    'admin.menu.rep_weekly': 'ಸಾಪ್ತಾಹಿಕ ವರದಿಗಳು',
    'admin.menu.rep_monthly': 'ಮಾಸಿಕ ವರದಿಗಳು',
    'admin.menu.rep_custom': 'ಕಸ್ಟಮ್ ವರದಿಗಳು',
    'admin.menu.rep_export': 'ರಫ್ತು ಕೇಂದ್ರ',
    'admin.menu.set_general': 'ಸಾಮಾನ್ಯ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'admin.menu.set_branding': 'ಬ್ರ್ಯಾಂಡಿಂಗ್',
    'admin.menu.set_languages': 'ಭಾಷೆಗಳು',
    'admin.menu.set_gateway': 'ಪಾವತಿ ಗೇಟ್‌ವೇ',
    'admin.menu.set_email': 'ಇಮೇಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'admin.menu.set_sms': 'SMS ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'admin.menu.set_keys': 'API ಕೀಲಿಗಳು',
    'admin.menu.set_security': 'ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'admin.menu.admin_users': 'ಅಡ್ಮಿನ್ ನಿರ್ವಹಣೆ',
    'admin.menu.admin_roles': 'ಪಾತ್ರಗಳು ಮತ್ತು ಅನುಮತಿಗಳು',
    'admin.menu.admin_audit': 'ಆಡಿಟ್ ಲಾಗ್‌ಗಳು',
    'admin.menu.admin_activity': 'ಚಟುವಟಿಕೆ ಲಾಗ್‌ಗಳು',
    'admin.menu.ai_churn': 'ಬಳಕೆದಾರರ ನಿರ್ಗಮನ ಭವಿಷ್ಯ',
    'admin.menu.ai_trending': 'ಟ್ರೆಂಡಿಂಗ್ ವೀಡಿಯೊಗಳು',
    'admin.menu.ai_recs': 'ಬಳಕೆದಾರರ ಶಿಫಾರಸುಗಳು',
    'admin.menu.ai_time': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಉತ್ತಮ ಸಮಯ',
    'admin.menu.engage_likes': 'ಇಷ್ಟಗಳು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳು',
    'admin.menu.engage_comments': 'ಕಾಮೆಂಟ್‌ಗಳು',
    'admin.menu.engage_reviews': 'ವಿಮರ್ಶೆಗಳು ಮತ್ತು ರೇಟಿಂಗ್‌ಗಳು',
    'admin.menu.engage_watchlist': 'ವೀಕ್ಷಣೆ ಪಟ್ಟಿ ವಿಶ್ಲೇಷಣೆ',
    'admin.menu.mon_live': 'ಲೈವ್ ಬಳಕೆದಾರರು',
    'admin.menu.mon_sys': 'ಸಿಸ್ಟಮ್ ಲಾಗ್‌ಗಳು',
    'admin.menu.mon_err': 'ದೋಷ ಲಾಗ್‌ಗಳು',
    'admin.menu.mon_storage': 'ಸಂಗ್ರಹಣೆ ಬಳಕೆ',
    'admin.menu.mon_transcode': 'ವೀಡಿಯೊ ಪ್ರಕ್ರಿಯೆ ಸ್ಥಿತಿ',
    
    // New Overview metrics
    'admin.dashboard.totalVideosUploaded': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಒಟ್ಟು ವೀಡಿಯೊಗಳು',
    'admin.dashboard.dailyWatchTime': 'ದೈನಂದಿನ ವೀಕ್ಷಣೆ ಸಮಯ',
    'admin.dashboard.monthlyWatchTime': 'ಮಾಸಿಕ ವೀಕ್ಷಣೆ ಸಮಯ',
    'admin.dashboard.liveStreamsRunning': 'ಚಾಲನೆಯಲ್ಲಿರುವ ಲೈವ್ ಸ್ಟ್ರೀಮ್‌ಗಳು',
    'admin.dashboard.topTrendingVideos': 'ಟಾಪ್ ಟ್ರೆಂಡಿಂಗ್ ವೀಡಿಯೊಗಳು',
    'admin.dashboard.trendingCategories': 'ಟ್ರೆಂಡಿಂಗ್ ವಿಭಾಗಗಳು',
    'admin.dashboard.watchTimePerVideo': 'ಪ್ರತಿ ವೀಡಿಯೊಗೆ ವೀಕ್ಷಣೆ ಸಮಯ',
    'admin.dashboard.avgSessionDuration': 'ಸರಾಸರಿ ಸೆಷನ್ ಅವಧಿ',
    'admin.dashboard.dropOffRate': 'ಡ್ರಾಪ್-ಆಫ್ ದರ',
    'admin.dashboard.completionRate': 'ಪೂರ್ಣಗೊಂಡ ದರ',
    'admin.dashboard.pendingApprovals': 'ಬಾಕಿ ಉಳಿದಿರುವ ಅನುಮೋದನೆಗಳು',
    'admin.dashboard.reportedVideos': 'ವರದಿಯಾದ ವೀಡಿಯೊಗಳು',
    'admin.statNewRegistrationsToday': 'ಇಂದು ಹೊಸ ನೋಂದಣಿಗಳು',
    
    // New Admin actions
    'admin.action.ban': 'ನಿರ್ಬಂಧಿಸಿ (Ban)',
    'admin.action.unban': 'ನಿರ್ಬಂಧ ತೆಗೆದುಹಾಕಿ (Unban)',
    'admin.action.suspend': 'ಅಮಾನತುಗೊಳಿಸಿ (Suspend)',
    'admin.action.unsuspend': 'ಅಮಾನತು ಹಿಂಪಡೆಯಿರಿ (Unsuspend)',
    'admin.action.refund': 'ಮರುಪಾವತಿ (Refund)',
    'admin.action.resolve': 'ಪರಿಹರಿಸಿ (Resolve)',
    'admin.action.approve': 'ಅನುಮೋದಿಸಿ',
    'admin.action.reject': 'ತಿರಸ್ಕರಿಸಿ',
    'admin.action.addAdmin': 'ಅಡ್ಮಿನ್ ಸೇರಿಸಿ',
    'admin.action.createPlan': 'ಯೋಜನೆ ರಚಿಸಿ',
    'admin.action.updatePlan': 'ಯೋಜನೆ ನವೀಕರಿಸಿ',
    'admin.action.deletePlan': 'ಯೋಜನೆ ಅಳಿಸಿ',
    'admin.action.saveSettings': 'ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಸಿ',
    'admin.action.sendCampaign': 'ಪ್ರಚಾರ ಕಳುಹಿಸಿ',
    
    // New Analytics metrics
    'admin.analytics.dau': 'ದೈನಂದಿನ ಸಕ್ರಿಯ ಬಳಕೆದಾರರು (DAU)',
    'admin.analytics.mau': 'ಮಾಸಿಕ ಸಕ್ರಿಯ ಬಳಕೆದಾರರು (MAU)',
    'admin.analytics.newRegistrations': 'ಹೊಸ ನೋಂದಣಿಗಳು',
    'admin.analytics.retentionRate': 'ಬಳಕೆದಾರರ ಉಳಿಸಿಕೊಳ್ಳುವಿಕೆ ದರ (Retention)',
    'admin.analytics.churnRate': 'ಬಳಕೆದಾರರ ನಿರ್ಗಮನ ದರ (Churn)',
    'admin.analytics.deviceUsage': 'ಸಾಧನ ಬಳಕೆ',
    'admin.analytics.revenueByRegion': 'ಪ್ರದೇಶವಾರು ಆದಾಯ',
    'admin.analytics.premiumConversion': 'ಪ್ರೀಮಿಯಂ ಪರಿವರ್ತನೆ ದರ',
    'admin.analytics.bufferingRatio': 'ಬಫರಿಂಗ್ ಅನುಪಾತ',
    'admin.analytics.playbackFailures': 'ಪ್ಲೇಬ್ಯಾಕ್ ವೈಫಲ್ಯಗಳು',
    'admin.analytics.cdnPerformance': 'CDN ಪ್ರತಿಕ್ರಿಯೆ ವೇಗ',
    
    // New Monitoring metrics
    'admin.monitoring.systemResources': 'ಸಿಸ್ಟಮ್ ಸಂಪನ್ಮೂಲಗಳು',
    'admin.monitoring.cpuLoad': 'CPU ಲೋಡ್',
    'admin.monitoring.ramUsage': 'RAM ಬಳಕೆ',
    'admin.monitoring.storageUsage': 'S3 ಸಂಗ್ರಹಣೆ ಬಳಕೆ',
    'admin.monitoring.networkUsage': 'ನೆಟ್‌ವರ್ಕ್ ವಿಳಂಬ',
    'admin.monitoring.liveStreamsHealth': 'ಲೈವ್ ಸ್ಟ್ರೀಮಿಂಗ್ ಸ್ಥಿತಿ',
    'admin.monitoring.bitrate': 'ಬಿಟ್‌ರೇಟ್ (Bitrate)',
    'admin.monitoring.fps': 'ಎಫ್‌ಪಿಎಸ್ (FPS)',
    'admin.monitoring.failedLogins': 'ವಿಫಲ ಲಾಗಿನ್‌ಗಳು',
    'admin.monitoring.blockedIps': 'ಬ್ಲಾಕ್ ಮಾಡಲಾದ IPಗಳು',
    'admin.monitoring.alerts': 'ಲೈವ್ ಸಿಸ್ಟಮ್ ಎಚ್ಚರಿಕೆಗಳು'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key, defaultText = '') => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // Fallback to English
    if (translations['en'][key]) {
      return translations['en'][key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
